version: "3"
services:
  ironfish:
    image: ghcr.io/iron-fish/ironfish:latest
    network_mode: host
    container_name: ironfish
    volumes:
        - ${HOME}/.ironfish:/root/.ironfish
 
  graffiti:
    image: ghcr.io/iron-fish/ironfish:latest
    network_mode: host
    volumes:
        - ${HOME}/.ironfish:/root/.ironfish
    entrypoint: ["./bin/run", "config:set", "blockGraffiti", "${graffiti}"]
    depends_on:
        - ironfish

  miner:
    image: ghcr.io/iron-fish/ironfish:latest
    network_mode: host
    container_name: miner
    volumes:
        - ${HOME}/.ironfish:/root/.ironfish
    entrypoint: ["./bin/run", "miners:start", "--threads", "-1"]
    depends_on:
        - ironfish
        - graffiti
  
